version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mathlms
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      - DATABASE_CLIENT=pg
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=example
      - DB_NAME=mathlms
      - JWT_SECRET=change_me
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db-data:
